# Generated by Django 4.0.4 on 2022-06-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_civil_genero_region_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveBigIntegerField()),
                ('docente', models.CharField(max_length=30)),
            ],
        ),
    ]
