# Generated by Django 4.0.4 on 2022-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_personas_estadocivil_personas_genero_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id de Donación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('pago', models.CharField(max_length=100, verbose_name='Pago')),
                ('monto', models.CharField(max_length=200, verbose_name='Monto')),
                ('tarjeta', models.CharField(max_length=100, verbose_name='Tarjeta')),
                ('fecha_expira', models.CharField(max_length=100, verbose_name='Fecha de expiracion')),
                ('cvv', models.CharField(max_length=100, verbose_name='CVV')),
                ('comentario', models.CharField(blank=True, max_length=100, verbose_name='Comentario')),
            ],
        ),
        migrations.DeleteModel(
            name='Civil',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
