# Generated by Django 4.0.4 on 2022-06-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Rut')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('conficontraseña', models.CharField(max_length=100, verbose_name='Confirmar Contraseña')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
    ]
