# Generated by Django 4.0.4 on 2022-06-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
    ]
