# Generated by Django 4.0.4 on 2022-06-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personas',
        ),
    ]
