# Generated by Django 4.0.4 on 2022-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personas_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='estadocivil',
            field=models.CharField(default=0, max_length=100, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='genero',
            field=models.CharField(default=0, max_length=100, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
