# Generated by Django 4.0.3 on 2022-06-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_personas_estadocivil_personas_genero_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonasDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('pago', models.CharField(max_length=100, verbose_name='Pago')),
                ('monto', models.CharField(max_length=200, verbose_name='Monto')),
                ('tarjeta', models.CharField(max_length=100, verbose_name='Tarjeta')),
                ('fecha_expira', models.CharField(max_length=100, verbose_name='Fecha de expiracion')),
                ('cvv', models.CharField(max_length=100, verbose_name='CVV')),
                ('comentario', models.CharField(max_length=100, verbose_name='Comentario')),
            ],
        ),
    ]
