# Generated by Django 4.0.3 on 2022-06-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_personasdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasdon',
            name='monto',
            field=models.CharField(max_length=7, verbose_name='Monto'),
        ),
    ]
