# Generated by Django 4.0.3 on 2022-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_personasdon_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personasdon',
            name='id',
        ),
        migrations.AlterField(
            model_name='personasdon',
            name='tarjeta',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tarjeta'),
        ),
    ]
